spring.application.name=banking-app
server.port  = 8087

encryption.key=1234567890123456

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/bankingDb
spring.datasource.username=postgres
spring.datasource.password=test

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
